namespace GuitarConfigurator.NetCore.Configuration.Types;

public enum SimpleType
{
    WiiInputSimple,
    Ps2InputSimple,
    WtNeckSimple,
    WtNeckPeripheralSimple,
    Gh5NeckSimple,
    CloneNeckSimple,
    DjTurntableSimple,
    UsbHost,
    Bluetooth,
    BluetoothTx,
    Led,
    Rumble,
    ConsoleMode,
    Reset,
    Midi,
    WiiOutputs,
    Peripheral,
    Mpr121,
    Max1704X,
    Ps2Outputs,
    FestivalKeyboard,
    FestivalGamepad,
    FestivalLayer,
    FestivalIos,
    Accel,
    ProGuitar,
}