namespace GuitarConfigurator.NetCore.Configuration.Types;

public enum UsbHostInputType
{
    X,
    A,
    B,
    Y,

    LeftShoulder,
    RightShoulder,

    Kick1,
    Kick2,

    Back,
    Start,

    LeftThumbClick,
    RightThumbClick,

    Guide,
    Capture,

    LeftBlue,
    LeftRed,
    LeftGreen,
    RightBlue,
    RightRed,
    RightGreen,
    SoloGreen,
    SoloRed,
    SoloYellow,
    SoloBlue,
    SoloOrange,

    Green,
    Red,
    Yellow,
    Blue,
    Orange,
    DpadUp,
    DpadDown,
    DpadLeft,
    DpadRight,

    LeftTrigger,
    RightTrigger,

    LeftStickX,
    LeftStickY,
    RightStickX,
    RightStickY,

    PressureDpadUp,
    PressureDpadRight,
    PressureDpadLeft,
    PressureDpadDown,
    PressureL1,
    PressureR1,
    PressureTriangle,
    PressureCircle,
    PressureCross,
    PressureSquare,
    RedVelocity,
    YellowVelocity,
    BlueVelocity,
    GreenVelocity,
    OrangeVelocity,
    BlueCymbalVelocity,
    YellowCymbalVelocity,
    GreenCymbalVelocity,
    KickVelocity,
    Whammy,
    Tilt,
    Pickup,
    Slider,
    LeftTableVelocity,
    RightTableVelocity,
    EffectsKnob,
    Crossfader,
    AccelX,
    AccelZ,
    AccelY,
    Gyro,
    GenericButton1,
    GenericButton2,
    GenericButton3,
    GenericButton4,
    GenericButton5,
    GenericButton6,
    GenericButton7,
    GenericButton8,
    GenericButton9,
    GenericButton10,
    GenericButton11,
    GenericButton12,
    GenericButton13,
    GenericButton14,
    GenericButton15,
    GenericButton16,
    GenericAxisX,
    GenericAxisY,
    GenericAxisZ,
    GenericAxisRx,
    GenericAxisRy,
    GenericAxisRz,
    GenericAxisSlider,
    KeyboardInput,
    MouseAxis,
    MouseButton,
    ProKey,
    YellowCymbal,
    BlueCymbal,
    GreenCymbal
    
}