namespace GuitarConfigurator.NetCore.Configuration.Types;

public enum WiiInputType
{
    ClassicLeftStickX,
    ClassicLeftStickY,
    ClassicRightStickX,
    ClassicRightStickY,
    ClassicLeftTrigger,
    ClassicRightTrigger,
    DrumJoystickX,
    DrumJoystickY,
    
    GuitarJoystickX = 14,
    GuitarJoystickY,
    GuitarWhammy,
    GuitarTapBar,
    
    NunchukStickX,
    NunchukStickY,
    NunchukAccelerationX,
    NunchukAccelerationY,
    NunchukAccelerationZ,
    NunchukRotationPitch,
    NunchukRotationRoll,
    
    DjTurntableLeft,
    DjTurntableRight,
    DjCrossfadeSlider,
    DjEffectDial,
    DjStickX,
    DjStickY,
    
    UDrawPenX,
    UDrawPenY,
    UDrawPenPressure,
    
    DrawsomePenX,
    DrawsomePenY,
    DrawsomePenPressure,
    
    GuitarGreen,
    GuitarRed,
    GuitarYellow,
    GuitarBlue,
    GuitarOrange,
    GuitarTapAll,
    GuitarTapGreen,
    GuitarTapRed,
    GuitarTapYellow,
    GuitarTapBlue,
    GuitarTapOrange,
    GuitarMinus,
    GuitarPlus,
    GuitarStrumUp,
    GuitarStrumDown,
    
    DrumMinus = 57,
    DrumPlus,
    
    NunchukC = 60,
    NunchukZ,
    
    UDrawPenClick,
    UDrawPenButton1,
    UDrawPenButton2,
    
    TaTaConLeftDrumRim,
    TaTaConLeftDrumCenter,
    TaTaConRightDrumRim,
    TaTaConRightDrumCenter,
    
    DjHeroEuphoria,
    DjHeroLeftGreen,
    DjHeroLeftRed,
    DjHeroLeftBlue,
    DjHeroRightGreen,
    DjHeroRightRed,
    DjHeroRightBlue,
    DjHeroMinus,
    DjHeroPlus,
    
    ClassicA,
    ClassicB,
    ClassicX,
    ClassicY,
    ClassicDPadUp,
    ClassicDPadDown,
    ClassicDPadLeft,
    ClassicDPadRight,
    ClassicZl,
    ClassicZr,
    ClassicLt,
    ClassicRt,
    ClassicPlus,
    ClassicMinus,
    ClassicHome,
    JoystickToDpad,
    GuitarPedal
}