//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantrollerConfiguratorBuilder.NetCore.ViewModels {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SantrollerConfiguratorBuilder.NetCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string WelcomeDesc {
            get {
                return ResourceManager.GetString("WelcomeDesc", resourceCulture);
            }
        }
        
        public static string ToolName {
            get {
                return ResourceManager.GetString("ToolName", resourceCulture);
            }
        }
        
        public static string NoConfigurations {
            get {
                return ResourceManager.GetString("NoConfigurations", resourceCulture);
            }
        }
        
        public static string NoDevices {
            get {
                return ResourceManager.GetString("NoDevices", resourceCulture);
            }
        }
        
        public static string SelectedToolLabel {
            get {
                return ResourceManager.GetString("SelectedToolLabel", resourceCulture);
            }
        }
        
        public static string SelectedToolNameLabel {
            get {
                return ResourceManager.GetString("SelectedToolNameLabel", resourceCulture);
            }
        }
        
        public static string SelectedDeviceHelpLabel {
            get {
                return ResourceManager.GetString("SelectedDeviceHelpLabel", resourceCulture);
            }
        }
        
        public static string PrimaryColorLabel {
            get {
                return ResourceManager.GetString("PrimaryColorLabel", resourceCulture);
            }
        }
        
        public static string WarningColorLabel {
            get {
                return ResourceManager.GetString("WarningColorLabel", resourceCulture);
            }
        }
        
        public static string ErrorColorLabel {
            get {
                return ResourceManager.GetString("ErrorColorLabel", resourceCulture);
            }
        }
        
        public static string LogoLabel {
            get {
                return ResourceManager.GetString("LogoLabel", resourceCulture);
            }
        }
        
        public static string LogoButtonLabel {
            get {
                return ResourceManager.GetString("LogoButtonLabel", resourceCulture);
            }
        }
        
        public static string SaveUF2Label {
            get {
                return ResourceManager.GetString("SaveUF2Label", resourceCulture);
            }
        }
        
        public static string SelectedDeviceTypeLabel {
            get {
                return ResourceManager.GetString("SelectedDeviceTypeLabel", resourceCulture);
            }
        }
        
        public static string SelectedDeviceNameLabel {
            get {
                return ResourceManager.GetString("SelectedDeviceNameLabel", resourceCulture);
            }
        }
        
        public static string SelectedDeviceVendorLabel {
            get {
                return ResourceManager.GetString("SelectedDeviceVendorLabel", resourceCulture);
            }
        }
        
        public static string ConfigureSelectedDevice {
            get {
                return ResourceManager.GetString("ConfigureSelectedDevice", resourceCulture);
            }
        }
        
        public static string WriteConfig {
            get {
                return ResourceManager.GetString("WriteConfig", resourceCulture);
            }
        }
        
        public static string SaveAndReturn {
            get {
                return ResourceManager.GetString("SaveAndReturn", resourceCulture);
            }
        }
        
        public static string SaveConfigTool {
            get {
                return ResourceManager.GetString("SaveConfigTool", resourceCulture);
            }
        }
        
        public static string PackageTool {
            get {
                return ResourceManager.GetString("PackageTool", resourceCulture);
            }
        }
        
        public static string CreateVariant {
            get {
                return ResourceManager.GetString("CreateVariant", resourceCulture);
            }
        }
        
        public static string RemoveVariant {
            get {
                return ResourceManager.GetString("RemoveVariant", resourceCulture);
            }
        }
        
        public static string ConfigIncomplete {
            get {
                return ResourceManager.GetString("ConfigIncomplete", resourceCulture);
            }
        }
        
        public static string UniqueName {
            get {
                return ResourceManager.GetString("UniqueName", resourceCulture);
            }
        }
    }
}
