permissions:
  contents: write
name: Build
on: [push]
jobs:
  build-mac:
    name: Build (macOS)
    runs-on: [self-hosted, macos]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: codesign
        id: codesign
        uses: apple-actions/import-codesign-certs@master
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
          keychain: ${{ github.run_id }}
          keychain-password: ${{ github.run_id }}
      - name: Build
        run: |
          cd Branded
          dotnet publish -c Release -r osx-x64 -t:BundleApp -p:RuntimeIdentifier=osx-x64 -p:UseAppHost=true --self-contained --verbosity normal
          mkdir out_stage
          mkdir out
          cp -r bin/Release/net7.0/osx-x64/publish/SantrollerConfiguratorBranded.app out_stage
          cp Resources/* out_stage
          cd out_stage
          N=5
          find "SantrollerConfiguratorBranded.app/Contents/MacOS" | while read fname; do
            ((i=i%N)); ((i++==0)) && wait
            if [[ -f $fname ]] && [ "$fname" != "SantrollerConfiguratorBranded.app/Contents/MacOS/SantrollerConfiguratorBranded" ]; then
            echo "[INFO] Signing $fname"
            codesign --force --timestamp --entitlements "entitlements.xml" --sign "guitar-configurator" "$fname" &
            fi
          done
          wait
          codesign --force --timestamp --entitlements "entitlements.xml" --sign "guitar-configurator" "SantrollerConfiguratorBranded.app/Contents/MacOS/SantrollerConfiguratorBranded"
          codesign --force --timestamp --options=runtime --entitlements "entitlements.xml" --sign "guitar-configurator" "SantrollerConfiguratorBranded.app"
          zip -r ../out/SantrollerConfiguratorBranded-macOS.zip SantrollerConfiguratorBranded.app
          cd ..
          mv out ..
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          mkdir $RUN_ID
          mv out $RUN_ID/macos 
          scp -r $RUN_ID sanjay@192.168.0.79:./artifacts
  build-linux:
    name: Build (Linux)
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: |
          cd Branded
          dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true --verbosity normal
          mkdir out
          cp bin/Release/net7.0/linux-x64/publish/SantrollerConfiguratorBranded out/SantrollerConfiguratorBranded-linux-64
          mv out ..
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          mkdir $RUN_ID
          mkdir -p ~/artifacts/$RUN_ID
          mv out ~/artifacts/$RUN_ID/linux 
  build-windows:
    name: Build (Windows)
    runs-on: [self-hosted, windows]
    steps:
      - name: git configure long path
        run: git config --global core.longpaths true
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: |
          cd Branded
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true --verbosity normal
          mkdir out
          cp bin/Release/net7.0/win-x64/publish/SantrollerConfiguratorBranded.exe out/SantrollerConfiguratorBranded-win-64.exe
          mv out ..
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          mkdir $Env:RUN_ID
          mv out $Env:RUN_ID/windows 
          scp -r $Env:RUN_ID sanjay@192.168.0.79:./artifacts
  build-linux-builder:
    name: Build Builder (Linux)
    needs: [build-linux, build-mac, build-windows]
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          cp ~/artifacts/$RUN_ID/windows/*.exe Builder/Assets
          cp ~/artifacts/$RUN_ID/linux/* Builder/Assets
          cp ~/artifacts/$RUN_ID/macos/*.zip Builder/Assets
      - name: Build
        run: |
          cd Builder
          dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true --verbosity normal
          mkdir out
          cp bin/Release/net7.0/linux-x64/publish/SantrollerConfiguratorBuilder out/SantrollerConfiguratorBuilder-linux-64
          mv out ..
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          mv out ~/artifacts/$RUN_ID/linux-builder
  build-windows-builder:
    name: Build Builder (Windows)
    needs: [build-linux, build-mac, build-windows]
    runs-on: [self-hosted, windows]
    steps:
      - name: git configure long path
        run: git config --global core.longpaths true
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          scp -r sanjay@192.168.0.79:./artifacts/$Env:RUN_ID .
          cp $Env:RUN_ID/windows/*.exe Builder/Assets
          cp $Env:RUN_ID/linux/* Builder/Assets
          cp $Env:RUN_ID/macos/*.zip Builder/Assets
      - name: Build
        run: |
          cd Builder
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true --verbosity normal
          mkdir out
          cp bin/Release/net7.0/win-x64/publish/SantrollerConfiguratorBuilder.exe out/SantrollerConfiguratorBuilder-win-64.exe
          mv out ..
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          mkdir -Force $Env:RUN_ID
          mv out $Env:RUN_ID/windows-builder 
          scp -r $Env:RUN_ID sanjay@192.168.0.79:./artifacts  
  build-mac-builder:
    name: Build Builder (macOS)
    needs: [ build-linux, build-mac, build-windows ]
    runs-on: [self-hosted, macos]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          scp -r sanjay@192.168.0.79:./artifacts/$RUN_ID .
          cp $RUN_ID/windows/*.exe Builder/Assets
          cp $RUN_ID/linux/* Builder/Assets
          cp $RUN_ID/macos/*.zip Builder/Assets
      - name: Build
        run: |
          cd Builder
          dotnet publish -c Release -r osx-x64 -t:BundleApp -p:RuntimeIdentifier=osx-x64 -p:UseAppHost=true --self-contained --verbosity normal
          mkdir out_stage
          mkdir out
          cp -r bin/Release/net7.0/osx-x64/publish/SantrollerConfiguratorBuilder.app out_stage
          cp Resources/* out_stage
          cd out_stage
          N=5
          find "SantrollerConfiguratorBuilder.app/Contents/MacOS" | while read fname; do
            ((i=i%N)); ((i++==0)) && wait
            if [[ -f $fname ]] && [ "$fname" != "SantrollerConfiguratorBuilder.app/Contents/MacOS/SantrollerConfiguratorBuilder" ]; then
            echo "[INFO] Signing $fname"
            codesign --force --timestamp --entitlements "entitlements.xml" --sign "guitar-configurator" "$fname" &
            fi
          done
          wait
          codesign --force --timestamp --entitlements "entitlements.xml" --sign "guitar-configurator" "SantrollerConfiguratorBuilder.app/Contents/MacOS/SantrollerConfiguratorBuilder"
          codesign --force --timestamp --options=runtime --entitlements "entitlements.xml" --sign "guitar-configurator" "SantrollerConfiguratorBuilder.app"
          zip -r ../out/SantrollerConfiguratorBuilder-macOS.zip SantrollerConfiguratorBuilder.app
          cd ..
          mv out ..
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          mkdir -p $RUN_ID
          mv out $RUN_ID/macos-builder 
          scp -r $RUN_ID sanjay@192.168.0.79:./artifacts
  release:
    if: contains(github.ref, 'tags/v')
    name: Release Build
    runs-on: [self-hosted, linux]
    needs: [build-linux, build-mac, build-windows, build-linux-builder, build-mac-builder, build-windows-builder]
    steps:
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          cp -r ~/artifacts/$RUN_ID/* .
          rm -rf ~/artifacts/$RUN_ID
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./windows/*.exe
            ./macos/*
            ./linux/*
            ./windows-builder/*.exe
            ./macos-builder/*
            ./linux-builder/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  pre-release:
    name: Release Preview Build
    runs-on: [self-hosted, linux]
    needs: [build-linux, build-mac, build-windows, build-mac-builder, build-linux-builder, build-windows-builder]
    steps:
      - name: Copy artifacts
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          cp -r ~/artifacts/$RUN_ID/* .
          rm -rf ~/artifacts/$RUN_ID
      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: preview
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: preview
          prerelease: true
          name: "Preview Build"
          body: "This build is not yet ready for use, the pipeline only exists for pipeline testing and does not actually function."
          files: |
            ./windows/*.exe
            ./macos/*
            ./linux/*
            ./windows-builder/*.exe
            ./macos-builder/*
            ./linux-builder/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
